- name: Import NodeJS Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install MySQL Client
  ansible.builtin.dnf:
    name:
      - mysql
      - python3-mysqlclient
    state: installed

#- name: Load Schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/{{ item }}.sql
#    login_host: mysql-{{ ENV }}.anilcloudengineer.online
#    login_user: root
#    login_password: RoboShop@1
#  loop:
#    - schema
#    - app-user
#    - master-data
- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-{{ ENV }}.anilcloudengineer.online -uroot -p"{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/shipping:MYSQL_ROOT_PASSWORD token={{ vault_token }} url=http://vault-internal.anilcloudengineer.online:8200') }}" </app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data